name: Code Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI_CHECKS: true

jobs:
  code-quality:
    if: github.repository == 'KonradSzwarc/zenith'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run checks
        run: npm run check

  visual-regression:
    if: github.repository == 'KonradSzwarc/zenith'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build the application
        run: npm run build
      - name: Create Percy snapshots
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy snapshot dist/
